
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true

  - script: |
      curl -L -o hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.164.0/hugo_extended_0.164.0_linux-amd64.deb
      sudo dpkg -i hugo.deb
      hugo --minify
    displayName: 'Build site with native Hugo'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/' 
      output_location: 'public'
      skip_app_build: true 
      azure_static_web_apps_api_token: $(deployment_token)


